 <!-- Start Footer 1 -->
			<footer id="footer">				
				<div class="footer-copyright">
					<div class="container">
						<div class="row">
								
							<div class="col-md-6 col-sm-12">
								<p>© 2015 All Rights Reserved. </p>
							</div>
							<div class="col-md-6 col-sm-12">
								<ul id="social-icons">
									<li><a href="#"><i class="icon ion-social-twitter"></i></a></li> 	
									<li><a href="#"><i class="icon ion-social-facebook"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-googleplus"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-instagram-outline"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-pinterest"></i></a></li>  
									<li><a href="#"><i class="icon ion-social-skype"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-linkedin"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-dropbox"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-vimeo"></i></a></li> 
									<li><a href="#"><i class="icon ion-social-youtube"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div><!-- End Footer Copyright -->
			</footer>
			<!-- End Footer 1 -->
			
			<!-- Start Back To Top -->
			<a id="back-to-top"><i class="icon ion-chevron-up"></i></a>
			<!-- End Back To Top -->
					  
		</div> <!-- End Site Wrapper --> 
		
		<!-- jQuery -->

		<script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>

		<script src="<?php echo AIOM::JS(array(
		
		'js/plugins/jquery.min.js',
		'js/plugins/moderniz.min.js',
		'js/plugins/smoothscroll.min.js',
		'js/plugins/revslider.min.js', 
		'js/plugins/bootstrap.min.js',
		'js/plugins/waypoints.min.js',
		'js/plugins/parallax.min.js',
		'js/plugins/easign1.3.min.js', 
		'js/plugins/cubeportfolio.min.js',
		'js/plugins/owlcarousel.min.js',
		
		'js/plugins/gmap3.min.js',
		'js/plugins/wow.min.js',
		'js/plugins/counterup.min.js',
		'js/plugins/masonry.js',  
		'js/scripts.js'
	)); ?>"></script>
		
	</body>
</html>